import { Project } from "./types";

export const APPS: Project[] = [
  {
    type: 'project',
    name: 'GasPump',
    blurb: 'Gaspump is a concentrated liquidity DEX in the Rise ecosystem, optimizing capital efficiency and minimizing slippage through narrow liquidity ranges. Dynamic fees and smart liquidity tools enhance trading and boost returns for liquidity providers.',
    logo: '/projects/gaspump/logo.png',
    banner: '/projects/gaspump/banner.png',
    status: 'live',
    x: 'https://x.com/Gaspump_swap',
    native: true,
    website: 'https://gaspump.network/swap',
    tags: ['DeFi', 'AMM', 'DEX'],
  },
  {
    type: 'project',
    name: 'For The Kingdom',
    blurb: "For The Kingdom is a web based MMORPG with a player driven economy and fully onchain gameplay. Players can risk tokens, create and monetize assets, and build custom logic and mods. Everything from game logic to world state lives on the blockchain.",
    logo: '/projects/forthekingdom/logo.png',
    banner: '/projects/forthekingdom/banner.png',
    status: 'live',
    x: 'https://x.com/4thekingdom_xyz',
    website: 'https://forthekingdom.xyz/',
    docs: 'https://docs.forthekingdom.xyz/ftk',
    native: true,
    tags: ['Gaming'],
  },
  {
    type: 'project',
    name: 'B3X',
    blurb: 'B3X is an onchain derivatives protocol building the World Market for World Computer.',
    logo: '/projects/b3x/logo.png',
    banner: '/projects/b3x/banner.png',
    status: 'live',
    x: 'https://x.com/b3xai',
    native: false,
    website: 'https://testnet.b3x.ai/',
    tags: ['DeFi', 'DEX'],
  },
  {
    type: 'project',
    name: 'GTX',
    blurb: 'Fully on-chain CLOB DEX on RISE Network. Efficient order-matching engine with DEX trustlessness. High-performance trading, low fees, and advanced order types.',
    logo: '/projects/gtx/logo.png',
    banner: '/projects/gtx/banner.png',
    status: 'coming soon',
    x: 'https://x.com/gtxfi_official',
    tags: ['DEX', 'DeFi'],
  },
  {
    type: 'project',
    name: 'Ultra',
    website: 'https://ultra-fi.xyz/',
    blurb: 'Ultra is a decentralized exchange (DEX) on the RISE Network. It is a fully on-chain CLOB DEX with a focus on high-performance trading and low fees.',
    logo: '/projects/ultra/logo.jpg',
    banner: '/projects/ultra/banner.jpg',
    status: 'coming soon',
    x: 'https://x.com/ultr2025',
    tags: ['DEX', 'DeFi'],
  },
  {
    type: 'project',
    name : 'NitroDex',
    blurb: 'NitroDex is a decentralized exchange (DEX) on the RISE Network. It is a fully on-chain CLOB DEX with a focus on high-performance trading and low fees.',
    logo: '/projects/nitrodex/logo.jpg',
    banner: '/projects/nitrodex/banner.jpg',
    status: 'live',
    website: 'https://www.nitrodex.xyz/',
    x: 'https://x.com/nitro_dex',
    native: false,
    tags: ['DEX', 'DeFi'],
  },
  {
    type: 'project',
    name: 'Standard',
    blurb: 'Trade high float, high cap Coins. Only on Standard, across all chains. Fully Onchain CLOB and Perps',
    logo: '/projects/standard/logo.png',
    banner: '/projects/standard/banner.png',
    status: 'live',
    website: 'https://linktr.ee/standardweb3',
    x: 'https://x.com/standardweb3',
    native: false,
    tags: ['DEX', 'DeFi'],
  },
  {
    type: 'project',
    name: 'Inari',
    blurb: 'Lend, Borrow and Earn with Inari Finance',
    logo: '/projects/inari/logo.jpg',
    banner: '/projects/inari/banner.png',
    status: 'live',
    website: 'https://inarifi.com',
    x: 'https://x.com/inari_fi',
    native: true,
    tags: ['DeFi', 'Yield'],
  },
  {
    type: 'project',
    name: 'LeoFi',
    blurb: 'LeoFi is a modular decentralized exchange (DEX) that redefines liquidity management and trading efficiency. It empowers traders with ultra-low fees and liquidity providers with customizable yield models via hook-integrated custom pools.',
    logo: '/projects/leofi/logo.jpg',
    banner: '/projects/leofi/banner.png',
    status: 'coming soon',
    x: 'https://x.com/LeoFi_Hub',
    website: 'https://etn.leofi.xyz/',
    native: false,
    tags: ['DEX', 'AMM', 'DeFi'],
  },
  {
    type: 'project',
    name: 'NFTs2Me',
    blurb: 'Create, deploy and manage your NFT collection and minting page with custom subdomain for free.',
    logo: '/projects/nft2me/logo.jpg',
    banner: '/projects/nft2me/banner.jpeg',
    status: 'live',
    website: 'https://nfts2me.com/app/rise-testnet/',
    native: false,
    x: 'https://x.com/NFTs2Me',
    tags: ['NFT'],
  },
  {
    type: 'project',
    name: 'Haifu',
    blurb: 'Chase Hype, Manage Wealth, with your AI Waifu',
    logo: '/projects/haifu/logo.png',
    banner: '/projects/haifu/banner.jpg',
    status: 'waitlist',
    website: 'https://haifu.fun/',
    x: 'https://x.com/haifudotfun',
    native: false,
    tags: ['AI', 'Waifu'],
  },  
  {
    type: 'project',
    name: 'NovaDubs',
    blurb: 'High Tech, Low Life, Fat Stacks. A full on-chain casino where you own a stake in the hustle.',
    logo: '/projects/novadubs/logo.png',
    banner: '/projects/novadubs/banner.png',
    status: 'waitlist',
    x: 'https://x.com/NovaDubsX',
    native: true,
    tags: ['Gaming', 'Casino'],
  },  
  {
    type: 'project',
    name: 'Relic',
    blurb: 'Relic is an NFT Marketplace dedicated to authentic, human expression in a digital world increasingly dominated by AI-generated content',
    logo: '/projects/relic/logo.png',
    banner: '/projects/relic/banner.png',
    status: 'waitlist',
    website: 'https://www.therelic.art/',
    x: 'https://x.com/relic_market',
    native: true,
    tags: ['NFT'],
  },  
  {
    type: 'project',
    name: 'NetSepio',
    docs: 'https://docs.netsepio.com/',
    x: 'https://x.com/netsepio',
    status: 'live',
    blurb: "NetSepio powers a DePIN-backed internet that’s private, secure, and agentic - connecting users and AI agents through trusted, decentralized networks.",
    logo: '/projects/netsepio/logo.png',
    banner: '/projects/netsepio/banner.png',
    website: 'https://netsepio.com/',
    native: false,
    tags: ['Data'],
  },
  {
    type: 'project',
    name: 'VeloxR',
    blurb: 'The fastest NFT marketplace based on and backed by the fastest block chain — Rise',
    status: 'live',
    logo: '/projects/VeloxR/logo.png',
    banner: '/projects/VeloxR/banner.png',
    website: 'https://veloxr.xyz/',
    x: 'https://x.com/r_velox',
    native: true,
    tags: ['NFT'],
  },
  {
    type: 'tooling',
    name: '42Agents.ai',
    blurb: '42 Agents easily integrates into your communication channels to offer you with round the clock customer support. No more \"wen token\" or \"why tx failed\" keeping your team up at night',
    logo: '/projects/42-agents-ai/logo.png',
    status: 'live',
    x: 'https://x.com/42agents_ai',
    website: 'https://www.42agents.ai',
    banner: '/projects/42-agents-ai/banner.png',
    tags: ['AI', 'DeFi'], // Choose from available tags in types.ts
  },
  {
    type: 'project',
    name: 'Omnihub',
    blurb: 'The launchpad for creating blockchain collectibles. Create, buy and sell as your most creative ideas come to life on OmniHub.',
    logo: '/projects/omnihub/logo.png',
    banner: '/projects/omnihub/banner.png',
    status: 'live',
    native: false,
    website: 'https://omnihub.xyz/',
    x: 'https://x.com/Omni_Hub',
    tags: ['NFT'],
  },
  {
    type: 'project',
    name: 'Centuari',
    blurb: 'Fixed-Rate Order Book Lending with Curated Vaults and Trust-Based Uncollateralized Borrowing',
    logo: '/projects/centuari/logo.png',
    banner: '/projects/centuari/banner.png',
    status: 'coming soon',
    x: 'https://x.com/CentuariLabs',
    tags: ["DeFi", "DAO", "Yield"],
  },
  {
    type: 'project',
    name: 'Stabilis',
    blurb: 'Native Stablecoin on RISE',
    logo: '/projects/stabilis/logo.png',
    banner: '/projects/stabilis/banner.png',
    status: 'coming soon',
    native: true,
    tags: ['DeFi', 'Yield'],
  },
]