import { Project } from './types';

export const projects: Project[] = [
  // Projects
  {
    type: 'project',
    name: 'GasPump',
    blurb: 'Gaspump is a concentrated liquidity DEX in the Rise ecosystem, optimizing capital efficiency and minimizing slippage through narrow liquidity ranges. Dynamic fees and smart liquidity tools enhance trading and boost returns for liquidity providers.',
    logo: '/projects/gaspump/logo.png',
    banner: '/projects/gaspump/banner.png',
    status: 'live',
    x: 'https://x.com/Gaspump_swap',
    website: 'https://gaspump.network/swap',
    tags: ['DeFi', 'AMM', 'DEX'],
  },
  {
    type: 'project',
    name: 'For The Kingdom',
    blurb: "For The Kingdom is a web based MMORPG with a player driven economy and fully onchain gameplay. Players can risk tokens, create and monetize assets, and build custom logic and mods. Everything from game logic to world state lives on the blockchain.",
    logo: '/projects/forthekingdom/logo.png',
    banner: '/projects/forthekingdom/banner.png',
    status: 'live',
    x: 'https://x.com/4thekingdom_xyz',
    website: 'https://forthekingdom.xyz/',
    docs: 'https://docs.forthekingdom.xyz/ftk',
    tags: ['Gaming'],
  },
  {
    type: 'project',
    name: 'B3X',
    blurb: 'B3X is an onchain derivatives protocol building the World Market for World Computer.',
    logo: '/projects/b3x/logo.png',
    banner: '/projects/b3x/banner.png',
    status: 'live',
    x: 'https://x.com/b3xai',
    website: 'https://testnet.b3x.ai/',
    tags: ['DeFi', 'DEX'],
  },
  {
    type: 'project',
    name: 'GTX',
    blurb: 'Fully on-chain CLOB DEX on RISE Network. Efficient order-matching engine with DEX trustlessness. High-performance trading, low fees, and advanced order types.',
    logo: '/projects/gtx/logo.png',
    banner: '/projects/gtx/banner.png',
    status: 'coming soon',
    x: 'https://x.com/gtxfi_official',
    tags: ['DEX', 'DeFi'],
  },
  {
    type: 'project',
    name: 'Ultra',
    website: 'https://ultra-fi.xyz/',
    blurb: 'Ultra is a decentralized exchange (DEX) on the RISE Network. It is a fully on-chain CLOB DEX with a focus on high-performance trading and low fees.',
    logo: '/projects/ultra/logo.jpg',
    banner: '/projects/ultra/banner.jpg',
    status: 'coming soon',
    x: 'https://x.com/ultr2025',
    tags: ['DEX', 'DeFi'],
  },
  {
    type: 'project',
    name : 'Clober',
    blurb: 'Clober delivers a fully on-chain order book infrastructure for DeFi. Supplying liquidity where AMMs won\'t dare.',
    logo: '/projects/clober/logo.png',
    banner: '/projects/clober/banner.png',
    status: 'live',
    website: 'https://rise.clober.io/',
    x: 'https://x.com/CloberDEX',
    tags: ['DEX', 'DeFi'],
  },
  {
    type: 'project',
    name: 'Standard',
    blurb: 'Trade high float, high cap Coins. Only on Standard, across all chains. Fully Onchain CLOB and Perps',
    logo: '/projects/standard/logo.png',
    banner: '/projects/standard/banner.png',
    status: 'live',
    website: 'https://linktr.ee/standardweb3',
    x: 'https://x.com/standardweb3',
    tags: ['DEX', 'DeFi'],
  },
  {
    type: 'project',
    name: 'Inari',
    blurb: 'Lend, Borrow and Earn with Inari Finance',
    logo: '/projects/inari/logo.jpg',
    banner: '/projects/inari/banner.png',
    status: 'live',
    website: 'https://inarifi.com',
    x: 'https://x.com/inari_fi',
    tags: ['DeFi', 'Yield'],
  },
  {
    type: 'project',
    name: 'LeoFi',
    blurb: 'LeoFi is a modular decentralized exchange (DEX) that redefines liquidity management and trading efficiency. It empowers traders with ultra-low fees and liquidity providers with customizable yield models via hook-integrated custom pools.',
    logo: '/projects/leofi/logo.jpg',
    banner: '/projects/leofi/banner.png',
    status: 'coming soon',
    x: 'https://x.com/LeoFi_Hub',
    website: 'https://etn.leofi.xyz/',
    tags: ['DEX', 'AMM', 'DeFi'],
  },
  {
    type: 'project',
    name: 'ChessOnChain',
    blurb: 'ChessOnChain is a decentralized, multi-chain chess gaming platform that enables players to compete, earn rewards, and own in-game assets as NFTs.',
    logo: '/projects/chessonchain/logo.jpg',
    banner: '/projects/chessonchain/banner.jpg',
    status: 'coming soon',
    x: 'https://x.com/ChessOnChain',
    website: 'https://play.chessonchain.io/',
    tags: ['Gaming'],
  },
  {
    type: 'project',
    name: 'NFTs2Me',
    blurb: 'Create, deploy and manage your NFT collection and minting page with custom subdomain for free.',
    logo: '/projects/nft2me/logo.jpg',
    banner: '/projects/nft2me/banner.jpeg',
    status: 'live',
    website: 'https://nfts2me.com/app/rise-testnet/',
    x: 'https://x.com/NFTs2Me',
    tags: ['NFT'],
  },
  {
    type: 'project',
    name: 'Haifu',
    blurb: 'Chase Hype, Manage Wealth, with your AI Waifu',
    logo: '/projects/haifu/logo.png',
    banner: '/projects/haifu/banner.jpg',
    status: 'waitlist',
    website: 'https://haifu.fun/',
    x: 'https://x.com/haifudotfun',
    tags: ['AI', 'Waifu'],
  },  
  {
    type: 'project',
    name: 'NovaDubs',
    blurb: 'High Tech, Low Life, Fat Stacks. A full on-chain casino where you own a stake in the hustle.',
    logo: '/projects/novadubs/logo.png',
    banner: '/projects/novadubs/banner.png',
    status: 'waitlist',
    x: 'https://x.com/NovaDubsX',
    tags: ['Gaming', 'Casino'],
  },  
  {
    type: 'project',
    name: 'Relic',
    blurb: 'Relic is an NFT Marketplace dedicated to authentic, human expression in a digital world increasingly dominated by AI-generated content',
    logo: '/projects/relic/logo.png',
    banner: '/projects/relic/banner.png',
    status: 'waitlist',
    website: 'https://www.therelic.art/',
    x: 'https://x.com/relic_market',
    tags: ['NFT'],
  },  
  {
    type: 'project',
    name: 'NetSepio',
    docs: 'https://docs.netsepio.com/',
    x: 'https://x.com/netsepio',
    status: 'live',
    blurb: "NetSepio powers a DePIN-backed internet that’s private, secure, and agentic - connecting users and AI agents through trusted, decentralized networks.",
    logo: '/projects/netsepio/logo.png',
    banner: '/projects/netsepio/banner.png',
    website: 'https://netsepio.com/',
    tags: ['Data'],
  },
  {
    type: 'project',
    name: 'VeloxR',
    blurb: 'The fastest NFT marketplace based on and backed by the fastest block chain — Rise',
    status: 'live',
    logo: '/projects/VeloxR/logo.png',
    banner: '/projects/VeloxR/banner.png',
    website: 'https://veloxr.netlify.app/',
    x: 'https://https://x.com/r_velox',
    tags: ['NFT'],
  },
  {
    type: 'project',
    name: 'OnChainGm',
    blurb: 'Your Daily Web3 Ritual',
    logo: '/projects/onchaingm/logo.jpg',
    banner: '/projects/onchaingm/banner.jpg',
    status: 'live',
    website: 'https://onchaingm.com/',
    x: 'https://x.com/OnChainGm',
    tags: [],
  },
  {
    type: 'project', // Choose from: 'project', 'infrastructure', or 'tooling'
    name: '42Agents.ai',
    blurb: '42 Agents easily integrates into your communication channels to offer you with round the clock customer support. No more \"wen token\" or \"why tx failed\" keeping your team up at night',
    logo: '/projects/42-agents-ai/logo.png',
    status: 'live',
    x: 'https://x.com/42agents_ai',
    website: 'https://www.42agents.ai',
    banner: '/projects/42-agents-ai/banner.png',
    tags: ['AI', 'DeFi'], // Choose from available tags in types.ts
  },
  {
    type: 'project',
    name: 'Omnihub',
    blurb: 'The launchpad for creating blockchain collectibles. Create, buy and sell as your most creative ideas come to life on OmniHub.',
    logo: '/projects/omnihub/logo.png',
    banner: '/projects/omnihub/banner.png',
    status: 'live',
    website: 'https://omnihub.xyz/',
    x: 'https://x.com/Omni_Hub',
    tags: ['NFT'],
  },
  // Tooling
  {
    type: 'tooling',
    name: 'Alchemy',
    blurb: 'Alchemy is a leading Web3 development platform that provides powerful tools and infrastructure for building decentralized applications.',
    logo: '/projects/alchemy/logo.png',
    banner: '/projects/alchemy/banner.png',
    status: 'live',
    website: 'https://alchemy.com/',
    tags: ['RPC', 'AA', 'NFT API', 'Token API', 'Data'],
  },
  {
    type: 'tooling',
    name: 'Goldsky',
    blurb: "Goldsky is Web3’s Realtime Data Platform. Build powerful dApps faster with high-performance blockchain indexing, instant subgraphs, and custom data streaming pipelines.",
    status: 'live',
    logo: '/projects/goldsky/logo.png',
    banner: '/projects/goldsky/banner.png',
    website: 'https://goldsky.com/',
    tags: ['Indexing', 'Data'],
  },
  {
    type: 'tooling',
    name: 'Stork',
    blurb: 'Stork’s Open Data Market unlocks access to decentralized, reliable, and unique data, empowering you to build your vision without compromise.',
    status: 'live',
    logo: '/projects/stork/logo.webp',
    banner: '/projects/stork/banner.webp',
    website: 'https://www.stork.network/',
    x: 'https://x.com/StorkOracle',
    tags: ['Oracles', 'Data'],
  },
  {
    type: 'tooling',
    name: 'Thirdweb',
    blurb: 'Thirdweb is a full stack web3 development platform with Frontend, backend, and onchain tools to build complete web3 apps — on every EVM chain, fully open-source.',
    logo: '/projects/thirdweb/logo.jpg',
    banner: '/projects/thirdweb/banner.png',
    status: 'live',
    website: 'https://thirdweb.com/',
    x: 'https://x.com/thirdweb',
    tags: ['RPC', 'AA', 'NFT API', 'Token API', 'Data'],
  },
  {
    type: 'tooling',
    name: 'Supra',
    blurb: 'Supra Oracles are a powerful cross-chain oracle network designed to power dApps across blockchain ecosystems with fast, secure, decentralized, and scalable data solutions.',
    status: 'live',
    logo: '/projects/supra/logo.png',
    banner: '/projects/supra/banner.png',
    website: 'https://supra.com/',
    x: 'https://x.com/SUPRA_labs',
    tags: ['Oracles', 'Data'],
  },
  {
    type: 'tooling',
    name: 'NetSepio',
    docs: 'https://docs.netsepio.com/',
    x: 'https://x.com/netsepio',
    blurb: "NetSepio powers a DePIN-backed internet that’s private, secure, and agentic - connecting users and AI agents through trusted, decentralized networks.",
    status: 'live',
    logo: '/projects/netsepio/logo.png',
    banner: '/projects/netsepio/banner.png',
    website: 'https://netsepio.com/',
    tags: ['Data'],
  },
  {
    type: 'tooling',
    name: 'ChainSight',
    docs: 'https://docs.chainsight.network/',
    x: 'https://x.com/Chainsight_',
    blurb: "Create, share, and scale onchain data pipelines.",
    status: 'live',
    logo: '/projects/chainsight/logo.png',
    banner: '/projects/chainsight/banner.png',
    website: 'https://chainsight.network/',
    tags: ['Oracles', 'Data'],
  },
  {
    type: 'tooling',
    name: 'Socket',
    blurb: 'SOCKET Protocol leverages Modular Order Flow Auctions (MOFA) to allow developers to Compose with any App, Users and Asset across Chains',
    status: 'live',
    logo: '/projects/socket/logo.svg',
    banner: '/projects/socket/banner.png',
    website: 'https://www.socket.tech/',
    x: 'https://x.com/socketprotocol',
    tags: ['Bridge'],
  },
  {
    type: 'tooling',
    name: 'Ponder',
    blurb: 'Ponder is an open-source backend framework for building robust, performant, and maintainable crypto apps',
    status: 'live',
    logo: '/projects/ponder/logo.png',
    banner: '/projects/ponder/banner.png',
    website: 'https://ponder.sh/',
    x: 'https://x.com/ponder_sh',
    tags: ['Data', 'Indexing'],
  },
  {
    type: 'tooling',
    name: 'Flipside',
    blurb: 'Growth platform for blockchains combining onchain data, wallet scoring, and community activation to make blockchain growth a precise, scientific art.',
    logo: '/projects/flipside/logo.png',
    banner: '/projects/flipside/banner.png',
    status: 'live',
    website: 'https://flipsidecrypto.xyz/',
    tags: ['Data', 'Indexing'],
  },
  {
    type: 'tooling',
    name: 'RubyScore',
    blurb: 'Analytics platform for blockchain and wallet, which combines on-chain data with a massive and constantly growing database containing millions of wallet labels.',
    logo: '/projects/rubyscore/logo.png',
    banner: '/projects/rubyscore/banner.png',
    status: 'live',
    website: 'https://rubyscore.io/',
    x: 'https://x.com/rubyscore_io',
    tags: ['Data'],
  },

  {
    type: 'tooling',
    name: 'Mud',
    blurb: 'Open-source engine for autonomous worlds. MUD reduces the complexity of building Ethereum apps with a tightly integrated software stack.',
    logo: '/projects/mud/logo.svg',
    banner: '/projects/mud/banner.png',
    status: 'live',
    website: 'https://mud.dev/',
    x: 'https://x.com/latticexyz',
    tags: [],
  },
];
