import { Project } from "./types";


export const TOOLS: Project[] = [
  {
    type: 'tooling',
    name: 'Alchemy',
    blurb: 'Alchemy is a leading Web3 development platform that provides powerful tools and infrastructure for building decentralized applications.',
    logo: '/projects/alchemy/logo.png',
    banner: '/projects/alchemy/banner.png',
    status: 'live',
    website: 'https://alchemy.com/',
    tags: ['RPC', 'AA', 'NFT API', 'Token API', 'Data'],
  },
  {
    type: 'tooling',
    name: 'Goldsky',
    blurb: "Goldsky is Web3’s Realtime Data Platform. Build powerful dApps faster with high-performance blockchain indexing, instant subgraphs, and custom data streaming pipelines.",
    status: 'live',
    logo: '/projects/goldsky/logo.png',
    banner: '/projects/goldsky/banner.png',
    website: 'https://goldsky.com/',
    tags: ['Indexing', 'Data'],
  },
  {
    type: 'tooling',
    name: 'Stork',
    blurb: 'Stork’s Open Data Market unlocks access to decentralized, reliable, and unique data, empowering you to build your vision without compromise.',
    status: 'live',
    logo: '/projects/stork/logo.webp',
    banner: '/projects/stork/banner.webp',
    website: 'https://www.stork.network/',
    x: 'https://x.com/StorkOracle',
    tags: ['Oracles', 'Data'],
  },
  {
    type: 'tooling',
    name: 'Thirdweb',
    blurb: 'Thirdweb is a full stack web3 development platform with Frontend, backend, and onchain tools to build complete web3 apps — on every EVM chain, fully open-source.',
    logo: '/projects/thirdweb/logo.jpg',
    banner: '/projects/thirdweb/banner.png',
    status: 'live',
    website: 'https://thirdweb.com/',
    x: 'https://x.com/thirdweb',
    tags: ['RPC', 'AA', 'NFT API', 'Token API', 'Data'],
  },
  {
    type: 'tooling',
    name: 'Supra',
    blurb: 'Supra Oracles are a powerful cross-chain oracle network designed to power dApps across blockchain ecosystems with fast, secure, decentralized, and scalable data solutions.',
    status: 'live',
    logo: '/projects/supra/logo.png',
    banner: '/projects/supra/banner.png',
    website: 'https://supra.com/',
    x: 'https://x.com/SUPRA_labs',
    tags: ['Oracles', 'Data'],
  },
  {
    type: 'tooling',
    name: 'NetSepio',
    docs: 'https://docs.netsepio.com/',
    x: 'https://x.com/netsepio',
    blurb: "NetSepio powers a DePIN-backed internet that’s private, secure, and agentic - connecting users and AI agents through trusted, decentralized networks.",
    status: 'live',
    logo: '/projects/netsepio/logo.png',
    banner: '/projects/netsepio/banner.png',
    website: 'https://netsepio.com/',
    tags: ['Data'],
  },
  {
    type: 'tooling',
    name: 'ChainSight',
    docs: 'https://docs.chainsight.network/',
    x: 'https://x.com/Chainsight_',
    blurb: "Create, share, and scale onchain data pipelines.",
    status: 'live',
    logo: '/projects/chainsight/logo.png',
    banner: '/projects/chainsight/banner.png',
    website: 'https://chainsight.network/',
    tags: ['Oracles', 'Data'],
  },
  {
    type: 'tooling',
    name: 'Socket',
    blurb: 'SOCKET Protocol leverages Modular Order Flow Auctions (MOFA) to allow developers to Compose with any App, Users and Asset across Chains',
    status: 'live',
    logo: '/projects/socket/logo.svg',
    banner: '/projects/socket/banner.png',
    website: 'https://www.socket.tech/',
    x: 'https://x.com/socketprotocol',
    tags: ['Bridge'],
  },
  {
    type: 'tooling',
    name: 'Ponder',
    blurb: 'Ponder is an open-source backend framework for building robust, performant, and maintainable crypto apps',
    status: 'live',
    logo: '/projects/ponder/logo.png',
    banner: '/projects/ponder/banner.png',
    website: 'https://ponder.sh/',
    x: 'https://x.com/ponder_sh',
    tags: ['Data', 'Indexing'],
  },
  {
    type: 'tooling',
    name: 'Flipside',
    blurb: 'Growth platform for blockchains combining onchain data, wallet scoring, and community activation to make blockchain growth a precise, scientific art.',
    logo: '/projects/flipside/logo.png',
    banner: '/projects/flipside/banner.png',
    status: 'live',
    website: 'https://flipsidecrypto.xyz/',
    tags: ['Data', 'Indexing'],
  },
  {
    type: 'tooling',
    name: 'RubyScore',
    blurb: 'Analytics platform for blockchain and wallet, which combines on-chain data with a massive and constantly growing database containing millions of wallet labels.',
    logo: '/projects/rubyscore/logo.png',
    banner: '/projects/rubyscore/banner.png',
    status: 'live',
    website: 'https://rubyscore.io/',
    x: 'https://x.com/rubyscore_io',
    tags: ['Data'],
  },
  {
    type: 'tooling',
    name: 'VIA Labs',
    blurb: 'VIA Labs equips developers with tools to scale across multiple blockchain networks, enabling seamless and efficient omnichain interoperability.',
    logo: '/projects/vialabs/logo.png',
    banner: '/projects/vialabs/banner.png',
    status: 'live',
    website: 'https://vialabs.io/',
    x: 'https://x.com/VIA_Labs',
    tags: ['Interoperability', 'Bridge', 'Oracles'],
  },
  {
    type: 'tooling',
    name: 'Mud',
    blurb: 'Open-source engine for autonomous worlds. MUD reduces the complexity of building Ethereum apps with a tightly integrated software stack.',
    logo: '/projects/mud/logo.svg',
    banner: '/projects/mud/banner.png',
    status: 'live',
    website: 'https://mud.dev/',
    x: 'https://x.com/latticexyz',
    tags: [],
  },
  {
    type: 'project',
    name: 'Centuari',
    blurb: 'Fixed-Rate Order Book Lending with Curated Vaults and Trust-Based Uncollateralized Borrowing',
    logo: '/projects/centuari/logo.png',
    banner: '/projects/centuari/banner.png',
    status: 'coming soon',
    x: 'https://x.com/CentuariLabs',
    tags: ["DeFi", "DAO", "Yield"],
  },
  {
    type: 'project',
    name: 'Stabilis',
    blurb: 'Native Stablecoin on RISE',
    logo: '/projects/stabilis/logo.png',
    banner: '/projects/stabilis/banner.png',
    status: 'coming soon',
    native: true,
    tags: ['DeFi', 'Yield'],
  },
  {
    type: 'tooling',
    name: 'AVA AI',
    blurb: 'AVA AI is an advanced Web3 infrastructure platform that leverages artificial intelligence to streamline decentralized app development. From smart contract generation and automated backend setup to voice/facial recognition and multi-chain deployment, AVA AI empowers developers to build, test, and deploy dApps faster and smarter. Designed for both beginners and enterprises, it bridges the gap between AI and blockchain by providing intuitive tools, natural language interfaces, and automated workflows.',
    logo: '/projects/AvaAILabs/logo.png',
    banner: '/projects/AvaAILabs/banner.png',
    status: 'waitlist',
    website: 'https://avaailabs.com/',
    x: 'https://x.com/AvaAiLabs',
    native: true,
    tags: ['AI']
  }
]